lib/Project.js, lib/Token.js, lib/descriptors/ProtoDescriptor.js, lib/parser.js, lib/tokenize.js, package.json, tests/parsing_test.js, tests/protoc_test.sh, tests/protos/kitchen-sink.proto, tests/protos/options.proto, tests/protos/person.proto, tests/protos/vehicle.proto
Hello @dpup, @tessr, 
Please review the following commits I made in branch 'nick-conformance'.
911c1ad99c03ffe3a109ddc0671601342acddb33 (2015-01-16 17:32:45 -0500)
Make test protos in pbnj protoc-compliant
R=@dpup
R=@tessr
Code Review Checklist:
=> Make test protos in pbnj protoc-compliant

lib/Project.js, package.json
Hello @nicks, @dpup,
Please review the following commits I made in branch 'jean-skipImports'.
5e2e1b3aaeadd773a7bd0acfbd7bf2de589da98d (2015-06-17 14:20:12 -0700)
Make opt_skipImports a project setting
R=@nicks
R=@dpup
=> Make opt_skipImports a project setting

lib/descriptors/FieldDescriptor.js, package.json, tests/parsing_test.js, tests/project_test.js, tests/protos/kitchen-sink.proto
Hello @jyhsu, 
Please review the following commits I made in branch 'nick-basetype'.
c752a5cb684a7ca8ce88d8999e1cb75fea9e20ed (2015-07-06 15:12:21 -0400)
add baseType to pbnj
R=@jyhsu
Test plan: 'unit'
=> add baseType to pbnj

package.json
Hello @nicks, 
Please review the following commits I made in branch 'nick-deps'.
4033c0b95e31472840d67e3802b8d7a18b90da68 (2015-07-06 15:34:38 -0400)
add nodeunit to devDeps instead of main deps
R=@nicks
=> add nodeunit to devDeps instead of main deps

lib/Project.js, tests/project_test.js, tests/protos/vehicle.proto
Hello @nicks,
Please review the following commits I made in branch 'jean-version'.
ec84867d5df42e525abaf80f05db4077bd552011 (2015-07-06 15:47:10 -0700)
Allow suffix-specific output directories for a project
R=@nicks
=> Allow suffix-specific output directories for a project

package.json
Hello @nicks,
Please review the following commits I made in branch 'jean-version'.
deb8594400a933425638a9837217c0cb72342258 (2015-07-07 10:46:09 -0700)
Bump version to 0.4.2
R=@nicks
=> Bump version to 0.4.2

lib/Project.js, package.json, tests/project_test.js
Hello @nicks,
Please review the following commits I made in branch 'jean-version'.
1761a3933a582c49d45a2b9fb1733a13f3d80ddd (2015-07-07 14:27:48 -0700)
compile does not generate files for imported protos
R=@nicks
=> compile does not generate files for imported protos

lib/Project.js
@jyhsu @nicks, please review. thanks.
=> add custom class name for ios

package.json
Hello @nicks, 
Please review the following commits I made in branch 'nick-bump'.
5964042129f550b2cee30558dc3e7540c5ebadce (2015-07-16 13:03:32 -0400)
bump package
R=@nicks
=> bump package

package.json
Hello @nicks, 
Please review the following commits I made in branch 'giannic-0.5.2'.
92610d646dbc7413655a02d5166076707da07b01 (2015-07-20 10:42:44 -0700)
bump package to 0.5.2
R=@nicks
=> bump package to 0.5.2

.travis.yml, README.md, tests/protoc_test.sh
Hello @nicks, 
Please review the following commits I made in branch 'nick-travis'.
f34bab4a1ba033e3b3e31868285af45b1101d1d3 (2015-07-22 18:11:31 -0400)
add pbnj to travis
R=@nicks
=> add pbnj to travis

lib/helper.js, tests/casing_test.js, tests/protos/conventions.proto
Hello @giannic, 
Please review the following commits I made in branch 'nick-camel'.
37a376169bde5c6dd13a53942e13ecbd8ff1fa69 (2015-07-22 17:49:08 -0400)
Tweak how we handle casing
R=@giannic
=> Tweak how we handle casing

lib/Project.js, lib/descriptors/ExtendDescriptor.js, lib/descriptors/ProtoDescriptor.js, lib/parser.js, tests/extensions_test.js, tests/protos/person.proto, tests/protos/super-person.proto
Hello @jyhsu, @giannic, 
Please review the following commits I made in branch 'nick-extend'.
1e62f83109db1c892b847d91613650770bc3ab9d (2015-07-24 19:13:08 -0400)
Add extends to pbnj. This will let us break cycles by letting us add fields later.
d37e4bf8f0416f52e0c2308758e864d0bc82820b (2015-07-22 17:28:49 -0400)
fix
R=@jyhsu
R=@giannic
TESTED=unit
=> Add extends to pbnj. This will let us break cycles by letting us add fields later.

package.json
Hello @nicks, 
Please review the following commits I made in branch 'nick-update'.
cce8444aaa7d15fbfc985db86ca8af5496f9922f (2015-07-29 14:52:12 -0400)
bump pbnj version
R=@nicks
TESTED=not tested
=> bump pbnj version

lib/descriptors/MessageDescriptor.js, lib/helper.js, tests/casing_test.js
Hello @giannic, 
Please review the following commits I made in branch 'andrew-messageCamel'.
173b9e19c266d5c8c5febf4392f832b7ea036f1c (2015-09-16 11:11:17 -0700)
Add camel casing to Message template.
R=@giannic
TESTED=not tested
=> Add camel casing to Message template.

package.json
Hello @giannic, 
Please review the following commits I made in branch 'andrew-upgradeVersion'.
f9c0687244a5fe6187666b66189ac0cf613545cc (2015-09-16 13:06:05 -0700)
Increment the version.
R=@giannic
TESTED=not tested
=> Increment the version.

.eslintrc, .travis.yml, lib/Project.js, lib/descriptors/ExtendDescriptor.js, lib/descriptors/MessageDescriptor.js, lib/descriptors/ProtoDescriptor.js, lib/helper.js, lib/parser.js, lib/tokenize.js, package.json
Hello @nicks, 
Please review the following commits I made in branch 'nick-cleanup'.
c6610ff88437aa42522c2fc14a1f077fa9f3eaf6 (2015-10-08 09:47:35 -0700)
Add eslint to pbnj and other small cleanups
R=@nicks
MANUAL TESTING=not manually tested
=> Add eslint to pbnj and other small cleanups

package.json, tests/project_test.js
Hello @nicks, 
Please review the following commits I made in branch 'nick-resolve'.
660ec4661d267afca38122b9b1e0660a7916b30d (2015-10-21 09:49:09 -0700)
Use nodeunitq to simplify tests
R=@nicks
=> Use nodeunitq to simplify tests

lib/descriptors/MessageDescriptor.js, tests/project_test.js
Hello @giannic, @jyhsu, 
Please review the following commits I made in branch 'nick-remove'.
ba72134afe08ddcc274394f940912e168f5547cc (2015-10-21 11:07:44 -0700)
add an api for removing proto fields
R=@giannic
R=@jyhsu
=> add an api for removing proto fields

lib/Project.js, lib/descriptors/EnumDescriptor.js, lib/descriptors/FieldDescriptor.js, lib/descriptors/ProtoDescriptor.js, tests/project_test.js
Hello @giannic, @jyhsu, 
Please review the following commits I made in branch 'nick-resolve'.
a8b3ae52c2e8bad71902a39a4424a432e0ba34fe (2015-10-22 15:22:53 -0700)
Add type resolution to pnbj
R=@giannic
R=@jyhsu
=> Add type resolution to pnbj

lib/Project.js
Hello @nicks, 
Please review the following commits I made in branch 'nick-compiler'.
a0fcba2f1f4a4700df54dcc1aeb315be682a8469 (2015-10-23 11:49:23 -0700)
create a new soy compiler on every project, so that we don't stomp on the global soy context
R=@nicks
=> create a new soy compiler on every project, so that we don't stomp on the global soy context

lib/descriptors/FieldDescriptor.js, lib/descriptors/MessageDescriptor.js, tests/project_test.js, tests/protos/loop.proto
Hello @jyhsu, @giannic, 
Please review the following commits I made in branch 'nick-loop'.
5577a7fa60eb063d94d7cdc08566ce742bc90abb (2015-10-23 12:01:01 -0700)
fix an infinite loop in type resolution
R=@jyhsu
R=@giannic
=> fix an infinite loop in type resolution

lib/Project.js, lib/descriptors/EnumDescriptor.js, lib/descriptors/MessageDescriptor.js, lib/helper.js, tests/project_test.js, tests/protos/inner.proto
Hello @jyhsu, @giannic, 
Please review the following commits I made in branch 'nick-inner'.
746177e288efe11d8cb53913ef046f533be55827 (2015-10-26 15:52:14 -0400)
Add fully qualified name to type descriptors, and resolve inner messages better
R=@jyhsu
R=@giannic
=> Add fully qualified name to type descriptors, and resolve inner messages better

package.json
Hello @nicks, 
Please review the following commits I made in branch 'nick-release'.
5521106474f3dbbf02d14db54b0bbf12ea86ef3a (2015-10-28 17:49:41 -0400)
bump pbnj to 0.6
R=@nicks
=> bump pbnj to 0.6

.travis.yml, travis.sh
Hello @nicks, 
Please review the following commits I made in branch 'koop-upgrade-travis'.
f3f057720aa46c1dbac44ea8d9782c9c06cf7474 (2015-12-01 18:06:10 -0800)
Upgrade to container-based Travis CI infrastructure.
R=@nicks
=> Upgrade to container-based Travis CI infrastructure.

lib/descriptors/FieldDescriptor.js, lib/descriptors/MessageDescriptor.js, lib/descriptors/OneofDescriptor.js, lib/parser.js, tests/parsing_test.js, tests/project_test.js, tests/protos/kitchen-sink.proto
Hello @nicks, 
Please review the following commits I made in branch 'koop-oneof'.
5b69ba537faad0677b3e35aca669a534ba424c2c (2015-12-01 15:03:08 -0800)
Implement oneof keyword.
R=@nicks
=> Implement oneof keyword.

package.json
Hello @koop, 
Please review the following commits I made in branch 'koop-package-urls'.
bddcf2772fa64113e712d15e1bfcc7eb3165ff5f (2015-12-03 15:03:34 -0800)
Update URLs to pbnj repository.
R=@koop
=> Update URLs to pbnj repository.

package.json
Hello @koop, 
Please review the following commits I made in branch 'koop-061'.
522dfc4e7ee25d887d385c3f3053a4fc5afcde10 (2015-12-03 15:09:10 -0800)
Version 0.6.1.
R=@koop
=> Version 0.6.1.

package.json
Hello @nicks, 
Please review the following commits I made in branch 'daniel-version-0.6.2'.
42e9fef017100fe6723adc145d1f9fd0aa435082 (2015-12-07 12:57:15 -0800)
Version 0.6.2
R=@nicks
MANUAL TESTING=not manually tested
=> Version 0.6.2

lib/descriptors/FieldDescriptor.js, lib/descriptors/OneofDescriptor.js, lib/helper.js, tests/casing_test.js
Hello @koop, 
Please review the following commits I made in branch 'andrew-upperUnderscoreCase'.
54978ea9a9a2f167025c6ee22c3b8863dbecfbe8 (2015-12-08 13:37:57 -0800)
Add upper underscore case support.
R=@koop
TESTED=case test added.
=> Add upper underscore case support.

lib/helper.js, tests/casing_test.js, tests/parsing_test.js, tests/protos/kitchen-sink.proto
Hello @xiao, @andrew3886, 
Please review the following commits I made in branch 'joy-camel'.
9be2b0843b977807d47b4a2b1683d47899c8e4ee (2015-12-08 17:15:56 -0800)
Camel case numbers in proto fields.
R=@xiao
R=@andrew3886
=> Camel case numbers in proto fields.

CHANGELOG.md, package.json
Hello @xiao, @andrew3886, 
Please review the following commits I made in branch 'joy-version'.
8174ce6a5e640cbec2bc5aac82227d720c6bf602 (2015-12-09 12:47:42 -0800)
Version 0.7.0
R=@xiao
R=@andrew3886
=> Version 0.7.0

lib/Project.js
Hello @nicks, 
Please review the following commits I made in branch 'daniel-passthrough-compiler-options'.
9247f1dc63fba42a0db1e4da34876c8bcf930d0e (2016-06-06 20:39:15 -0700)
passthrough additional compiler options
R=@nicks
=> passthrough additional compiler options

package.json
Hello @nicks, 
Please review the following commits I made in branch 'nicks/bump'.
78d1cd81df4957be8f8e7729878466069c2a52c3 (2016-07-07 15:28:53 -0400)
bump version #
R=@nicks
=> bump version #

lib/helper.js, tests/project_test.js, tests/protos/services.proto
Hello @mikkot, 
Please review the following commits I made in branch 'daniel-fmt-upper'.
760ce2b7ca4ef667a747816820b600018ca2e8fc (2016-08-17 16:23:42 -0700)
fix upper-under formatting
R=@mikkot
=> fix upper-under formatting

lib/descriptors/ExtendDescriptor.js, lib/descriptors/FieldDescriptor.js, lib/descriptors/MessageDescriptor.js, lib/descriptors/MethodDescriptor.js, lib/descriptors/ProtoDescriptor.js, lib/descriptors/ServiceDescriptor.js, tests/project_test.js
Hello @dmccartney, 
Please review the following commits I made in branch 'nicks/lazy'.
6cdf8f2dcfb898a074f33d46dd6a6611a011c52c (2016-09-30 20:19:11 -0400)
Evaluate template objects lazily. Reduces medium protogen from 70s -> 2.5s
R=@dmccartney
=> Evaluate template objects lazily. Reduces medium protogen from 70s -> 2.5s

lib/descriptors/ProtoDescriptor.js, lib/parser.js, tests/parsing_test.js, tests/protos/common.proto, tests/protos/conventions.proto, tests/protos/inner.proto, tests/protos/kitchen-sink-v3.proto, tests/protos/loop.proto, tests/protos/options.proto, tests/protos/otherOptions.proto, tests/protos/person.proto, tests/protos/services.proto, tests/protos/super-person.proto, tests/protos/vehicle.proto
Hello @iraAlor, @kylewm, @silverlyra, @sachee, 
Please review the following commits I made in branch 'eduardoramirez/parse-proto-3'.
795d219a226add8730396188fc274b05b95cf02b (2018-06-20 01:46:17 -0700)
support parsing proto syntax 3
R=@iraAlor
R=@kylewm
R=@silverlyra
R=@sachee
=> support parsing proto syntax 3

lib/Token.js, lib/parser.js, lib/tokenize.js, package.json, tests/parsing_test.js, tests/protos/kitchen-sink.proto
Hello @silverlyra, @dangilk, 
Please review the following commits I made in branch 'sachee/bump-version'.
2a877d5d6005012f86635c807daa8b85bd8326c3 (2018-08-01 14:18:49 -0700)
bump version to 0.14.3
35749f3437e2cc86198fad380baa82f8eac336ea (2018-07-31 17:50:38 -0700)
space
b26696ce718638fcb8d59b757c3ec1026da6f2fe (2018-07-31 17:43:07 -0700)
added tests for block options
a3ffeba2929ad8a8a2a6656b9c2dacafc80257c7 (2018-07-31 17:43:07 -0700)
add tokens, tokenizing, and parsing for block options
R=@silverlyra
R=@dangilk
=> bump version to 0.14.3

lib/parser.js, package.json, tests/parsing_test.js, tests/protos/kitchen-sink.proto, tests/protos/options.proto
Please review the commits I made in branch 'eduardoramirez/parse-number-options'.
R=@aherrrera
R=@jfuchs
R=@jdmoody
R=@joshfrench
=> parse options with number values

tests/protos/options.proto
Please review the commits I made in branch 'eduardoramirez/fix-test'.
R=@aherrrera
R=@jfuchs
R=@jdmoody
R=@joshfrench
=> fix protoc test

lib/parser.js, package.json, tests/parsing_test.js, tests/protoc_test.sh, tests/protos/kitchen-sink.proto, tests/protos/options.proto
Please review the commits I made in branch 'eduardoramirez/support-multi-options'.
R=@aherrrera
R=@jfuchs
R=@jdmoody
R=@joshfrench
=> support parsing repeated msg options

lib/parser.js, package.json, tests/parsing_test.js, tests/protos/kitchen-sink.proto, tests/protos/options.proto
Please review the commits I made in branch 'eduardoramirez/parse-lists'.
R=@aherrrera
R=@jfuchs
R=@jdmoody
R=@joshfrench
=> support parsing lists in message & file options (and within options that are messages)

lib/parser.js, package.json, tests/parsing_test.js, tests/protos/kitchen-sink.proto, tests/protos/options.proto
Please review the commits I made in branch 'eduardoramirez/join-single-options'.
R=@aherrrera
R=@jfuchs
R=@jdmoody
R=@joshfrench
=> support repeated options that have a basic type

include/google/protobuf/duration.proto, include/google/protobuf/timestamp.proto
This adds includes for the Duration and Timestamp proto messages.
=> Add duration and timestamp includes
